/// Flutter icons MyIconsFace
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIconsFace
///      fonts:
///       - asset: fonts/MyIconsFace.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIconsFace {
  MyIconsFace._();

  static const _kFontFam = 'MyIconsFace';
  static const String? _kFontPkg = null;

  static const IconData angry = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shocked = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laughing = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
